import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useTheme } from '../hooks/useTheme';
import { BriefingArticle } from './BriefingArticle';
import { BriefingLoading } from './BriefingLoading';
import { Spacing } from '../theme';
import type { GeneratedBriefing } from '../services/anthropic';
import type { LanguageCode, LanguageLevel, Topics } from '../store/useSettingsStore';

// Maps the genre strings the API returns to settings topic keys
const GENRE_TO_TOPIC: Record<string, keyof Topics> = {
  'GLOBAL NEWS': 'worldNews',
  'POLITICS': 'politics',
  'BUSINESS & ECONOMY': 'business',
  'SCIENCE & TECHNOLOGY': 'scienceTech',
  'ARTS & CULTURE': 'artsCulture',
  'GOOD NEWS': 'goodNews',
};

// C1 displays as "C1 / Native" in the language being learned
const C1_LABEL: Record<LanguageCode, string> = {
  en: 'C1 / Native',
  fr: 'C1 / Natif',
  de: 'C1 / Muttersprachlich',
  es: 'C1 / Nativo',
  it: 'C1 / Madrelingua',
};

interface Props {
  langCode: LanguageCode;
  nativeName: string;
  level: LanguageLevel;
  briefing: GeneratedBriefing | undefined;
  isGenerating: boolean;
  error: string | undefined;
  isFirst: boolean;
  topics: Topics;
  onRetry: () => void;
}

function formatTime(ts: number): string {
  return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
}

function levelLabel(level: LanguageLevel, langCode: LanguageCode): string {
  if (level === 'C1' || level === 'C2' || level === 'Native') {
    return C1_LABEL[langCode] ?? 'C1 / Native';
  }
  return level;
}

export function LanguageBriefingSection({
  langCode,
  nativeName,
  level,
  briefing,
  isGenerating,
  error,
  isFirst,
  topics,
  onRetry,
}: Props) {
  const { colors, fontFamily, fontSize } = useTheme();

  // Filter articles by enabled topics (client-side — no extra API call needed)
  const visibleArticles = briefing?.articles.filter((a) => {
    const topicKey = GENRE_TO_TOPIC[a.genre.toUpperCase()];
    if (!topicKey) return true;
    return topics[topicKey] !== false;
  }) ?? [];

  const hasContent = visibleArticles.length > 0;

  return (
    <View>
      {!isFirst && <View style={[styles.separator, { backgroundColor: colors.borderLight }]} />}

      {/* Edition header — newspaper style */}
      <View style={[styles.editionRow, { borderTopColor: colors.inkDark, borderBottomColor: colors.inkDark }]}>
        <View style={[styles.editionRule, { backgroundColor: colors.inkDark }]} />
        <Text style={[styles.editionText, { color: colors.inkMid, fontFamily: fontFamily.regular }]}>
          {nativeName.toUpperCase()} · {levelLabel(level, langCode)}
        </Text>
        <View style={[styles.editionRule, { backgroundColor: colors.inkDark }]} />
      </View>
      <View style={[styles.mastRule, { backgroundColor: colors.inkDark }]} />

      {(isGenerating || (!error && !briefing)) && <BriefingLoading />}

      {!isGenerating && error && (
        <View style={styles.centerBlock}>
          <Ionicons name="alert-circle-outline" size={36} color={colors.inkFaint} />
          <Text style={[styles.errorText, { color: colors.inkMid, fontFamily: fontFamily.regular, fontSize: fontSize.body }]}>
            {error}
          </Text>
          <TouchableOpacity style={[styles.button, { borderColor: colors.borderMid }]} onPress={onRetry}>
            <Text style={[styles.buttonText, { color: colors.inkMid, fontFamily: fontFamily.regular }]}>
              Try again
            </Text>
          </TouchableOpacity>
        </View>
      )}

      {!isGenerating && !error && briefing && !hasContent && (
        <View style={styles.centerBlock}>
          <Text style={[styles.emptyNote, { color: colors.inkFaint, fontFamily: fontFamily.italic }]}>
            All topics are hidden — turn some on in Settings to read the briefing.
          </Text>
        </View>
      )}

      {hasContent && (
        <>
          {visibleArticles.map((article, index) => (
            <BriefingArticle
              key={`${article.genre}-${index}`}
              article={article}
              isLast={index === visibleArticles.length - 1}
              language={langCode}
              level={level}
              locked={false}
              onLockedWordPress={() => {}}
            />
          ))}

          <View style={[styles.sectionFooter, { borderTopColor: colors.borderLight }]}>
            <Text style={[styles.footerText, { color: colors.inkFaint, fontFamily: fontFamily.italic }]}>
              {briefing?.generatedAt
                ? `Claude API · ${formatTime(briefing.generatedAt)} · Live web search`
                : 'Generated by Claude with live web search'}
            </Text>
          </View>
        </>
      )}
    </View>
  );
}

const styles = StyleSheet.create({
  separator: {
    height: 2,
    marginTop: Spacing.xl,
  },
  editionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    marginTop: Spacing.sm,
  },
  editionRule: { flex: 1, height: 1 },
  editionText: { fontSize: 11, letterSpacing: 1.5, paddingHorizontal: Spacing.sm },
  mastRule: { height: 1, marginHorizontal: Spacing.md, marginBottom: Spacing.xs },
  centerBlock: {
    alignItems: 'center',
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.xxl,
    paddingBottom: Spacing.xl,
    gap: Spacing.md,
  },
  errorText: { textAlign: 'center', lineHeight: 24 },
  button: {
    borderWidth: 1,
    borderRadius: 6,
    paddingHorizontal: Spacing.lg,
    paddingVertical: Spacing.sm,
  },
  buttonText: { fontSize: 15 },
  emptyNote: { fontSize: 13, textAlign: 'center' },
  sectionFooter: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    marginTop: Spacing.md,
  },
  footerText: { fontSize: 12 },
});
